@Watch.Manager.ApiService_HostAddress = https://localhost:7558

GET {{Watch.Manager.ApiService_HostAddress}}/analyse
Content-Type: application/json

{
    "UriToAnalyze": "https://andrewlock.net/behind-the-scenes-of-collection-expressions-part-5-adding-support-for-collection-expressions-to-your-own-types/"
}

###
