@Watch.Manager.ApiService_HostAddress = https://localhost:7558

POST {{Watch.Manager.ApiService_HostAddress}}/api/catalog/analyse?api-version=1.0
Content-Type: application/json

{
    "UriToAnalyze": "https://www.telerik.com/blogs/understanding-solid-principles"
}

###


GET {{Watch.Manager.ApiService_HostAddress}}/api/catalog/search?text=design+pattern&api-version=1.0
